from .publish.publish_asset import NODE_CLASS_MAPPINGS as PUBLISH_ASSET_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as PUBLISH_ASSET_NAME_MAPPINGS
from .publish.publish_blender import NODE_CLASS_MAPPINGS as PUBLISH_BLENDER_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as PUBLISH_BLENDER_NAME_MAPPINGS

WEB_DIRECTORY = "./web/js"

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(PUBLISH_ASSET_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(PUBLISH_ASSET_NAME_MAPPINGS)
NODE_CLASS_MAPPINGS.update(PUBLISH_BLENDER_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(PUBLISH_BLENDER_NAME_MAPPINGS)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', "WEB_DIRECTORY"]
