from .provenance.asset_provenance import NODE_CLASS_MAPPINGS as ASSET_PROVENANCE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as ASSET_PROVENANCE_NAME_MAPPINGS   
from .provenance.provenance_connector import NODE_CLASS_MAPPINGS as PROVENANCE_CONNECTOR_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as PROVENANCE_CONNECTOR_NAME_MAPPINGS

WEB_DIRECTORY = "./js"

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(ASSET_PROVENANCE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(ASSET_PROVENANCE_NAME_MAPPINGS)

NODE_CLASS_MAPPINGS.update(PROVENANCE_CONNECTOR_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(PROVENANCE_CONNECTOR_NAME_MAPPINGS)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', "WEB_DIRECTORY"]
