from typing import Optional
from pydantic import BaseModel, Field
from .version import model_name, model_version
from .seed import artist_names, shot_names, task_names, creative_work_names, script_revisions, character_names, scene_numbers
from .seed import get_artist_id, get_shot_id, get_task_id, get_creative_work_id, get_script_id, get_character_id, get_scene_id

class IdentifierModel(BaseModel):
    scope: str = Field(alias="identifierScope")
    value: str = Field(alias="identifierValue")
    class Config:
        populate_by_name = True

class AssetProvenanceModel(BaseModel):
    # generated by the tool
    batch_id: str = Field(default=None)
    # comes from production systems, such as ShotGrid
    shot_id: str = Field(default=None, alias="shotId")
    task_id: str = Field(default=None, alias="taskId")
    artist_id: str = Field(default=None, alias="artistId")
    setup: str = Field(default=None, alias="setup")
    take: str = Field(default=None, alias="take")
    # comes from narrative tracking systems, such as Yamdu
    creative_work: IdentifierModel = Field(alias="creativeWork")
    character: Optional[IdentifierModel] = Field(default=None, alias="character")
    scene: Optional[IdentifierModel] = Field(default=None, alias="scene")
    # comes from MAM
    script_id: IdentifierModel = Field(alias="script")
    # comes from the tool
    context: str = Field(description="Is the task considered direct production work (production) or something that helps with production eventually (narrative)?")
    asset_type: str = Field(description="The type of asset", alias="assetFunctionalType")
    class Config:
        populate_by_name = True

class AssetProvenance:
    def __init__(self):
        pass

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "artist_name": (artist_names,),
                "shot_name": (shot_names,),
                "task_name": (task_names,),
                "creative_work_name": (creative_work_names,),
                "script_revision": (script_revisions,),
                "context": (["production", "concept", "experimentation"], {"tooltip": "Is the task considered direct production work (production) or something that helps with production eventually (concept) or an experiment (experimentation)?"}),
                "asset_type": (["artwork",
                    "artwork.animatedStoryboard",
                    "artwork.conceptArt",
                    "artwork.storyboard",
                    "audio",
                    "audio.channel",
                    "audio.object",
                    "audio.objectMetadata",
                    "audio.onSetMix",
                    "audio.track",
                    "cameraMetadata",
                    "capture",
                    "capture.audio",
                    "capture.audio.wild",
                    "capture.calibration",
                    "capture.cameraProxy",
                    "capture.faceCamera",
                    "capture.lidar",
                    "capture.motionCapture",
                    "capture.ocf",
                    "capture.roll",
                    "capture.witnessCamera",
                    "cgModel",
                    "color",
                    "color.cdl",
                    "color.colorSpace",
                    "color.lut",
                    "configuration",
                    "configuration.colorSpace",
                    "costume",
                    "creativeReferenceMaterial",
                    "lensMetadata",
                    "map",
                    "material",
                    "productionCharacter",
                    "productionProp",
                    "productionProp.productionGreenery",
                    "productionProp.productionVehicle",
                    "productionSetDressing",
                    "productionSetDressing.productionGreenery",
                    "productionSetDressing.productionVehicle",
                    "proxy",
                    "proxy.daily",
                    "proxy.editorial",
                    "recorderMetadata",
                    "script",
                    "sequenceChronologyDescriptor",
                    "shot",
                    "shot.animation",
                    "shot.editorial",
                    "shot.vfx",
                    "technicalReferenceMaterial"
                  ],),
            },
            "optional": {
                "character_name": ([""] + character_names, {"default": ""}),
                "scene_number": ([""] + scene_numbers, {"default": ""}),
                "setup": ("STRING", {"default": "", "multiline": False}),
                "take": ("STRING", {"default": "", "multiline": False}),
            },
        }

    RETURN_TYPES = ("PROVENANCE",)
    RETURN_NAMES = ("provenance",)
    FUNCTION = "capture_provenance"
    OUTPUT_NODE = False
    CATEGORY = "MovieLabs > Util > Grant8&9"

    def capture_provenance(self, **kwargs):
        artist_id = get_artist_id(kwargs["artist_name"])
        shot_id = get_shot_id(kwargs["shot_name"])
        task_id = get_task_id(kwargs["task_name"])
        creative_work_id = get_creative_work_id(kwargs["creative_work_name"])
        script_id = get_script_id(kwargs["script_revision"])
        character_id = get_character_id(kwargs["character_name"]) if kwargs["character_name"] else None
        scene_id = get_scene_id(kwargs["scene_number"]) if kwargs["scene_number"] else None
        context = kwargs["context"]
        asset_type = kwargs["asset_type"]
        setup = kwargs["setup"]
        take = kwargs["take"]

        if context == "concept" and character_id is None:
            raise ValueError("Character is required for concept work")
        if context == "production" and scene_id is None:
            raise ValueError("Scene is required for production work")

        prov = AssetProvenanceModel(
            artist_id=artist_id,
            shot_id=shot_id,
            task_id=task_id,
            creative_work=IdentifierModel(identifierScope=creative_work_id[0], identifierValue=creative_work_id[1]),
            script_id=IdentifierModel(identifierScope=script_id[0], identifierValue=script_id[1]),
            character=IdentifierModel(identifierScope=character_id[0], identifierValue=character_id[1]) if character_id else None,
            scene=IdentifierModel(identifierScope=scene_id[0], identifierValue=scene_id[1]) if scene_id else None,
            context=context,
            asset_type=asset_type,
            setup=setup,
            take=take
        )
        provenance = {}
        model = {}
        model["modelName"] = model_name
        model["modelVersion"] = model_version
        provenance["model"] = model
        provenance["data"] = prov.model_dump(by_alias=True)
        return (provenance,)

NODE_CLASS_MAPPINGS = {
    "AssetProvenance": AssetProvenance
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "AssetProvenance": "Asset Provenance"
}
